export const allTexts = {
  buttonTexts: {
    // place all your button texts here
    start: 'Start Now',
    sigup: 'sign up',
    login: 'Log in',
    follow: 'Follow',
    unFollow: 'Un Follow',
    contactUs: 'Contact Us',
    next: 'Next',
    updatePassword: 'Update Password',
    add: 'Add',
    addevents: 'Add Event',
  },

  headings: {
    // place all your Heading texts here
    verfiyEmail: 'Verify your email Address',
    splashTitle: 'Start Explore your Best Temple',
    kovela: 'kovela',
    Addpoojari: 'Add Poojari',
    inputTitles: {
      fName: 'First name',
      phoneNo: 'phone number',
      lastName: 'last name',
      email: 'email',
      password: 'password',
      tName: 'Enter Temple Name',
      tDescription: 'Description',
      tCommunity: 'Community',
      confirmPassword: 'confirm password',
      pinCode: 'Pincode',
      line2: 'Line 2',
      line1: 'Line 1',
      line3: 'Line 3',
      addEmployeeId: 'Add Employee Id',
      eventname: 'Event Name',
      pickadate: 'Pick a date for darshan',
      feedevent: 'Add this Event to the Feed',
    },
    accountItems: {
      profile: 'profile',
      bookings: 'my bookings',
      donations: 'my donations',
      temple: 'my temples',
      donation: 'Donations',
      ticketBooking: 'Ticket Bookings',
      poojaTicket: 'Pooja Ticket',
      accmodation: 'Accomodation',
      occasion: 'Occasions',
    },
  },
  placeHolders: {
    fistNamePlace: 'Enter Your First Name',
    otpSend: 'Enter OTP sent to ',
    lastNamePlace: 'Enter Your last name',
    emailPlace: 'Enter Your email',
    passwordPlace: 'Enter Your password',
    confirmPasswordPlace: 'Enter Your confirm password',
    tampleNameP: 'Enter tample name here',
    tampleDescritionP: 'Enter Description here',
    communityP: 'Enter community here',
    pincodeP: 'Enter pincode here',
    line1P: 'Enter line1 here',
    line2P: 'Enter line2 here',
    line3P: 'Enter line3 here',
    poojarimailid: 'place holder email id',
    templeSearc: 'Temple search',
    poojariname: 'Poojari Name',
  },
  paragraphs: {
    alreadyAccount: 'Already have an account?',
    dontHaveAccount: 'Don’t have an account ?',
    splashDescription:
      'There are many destinations for your holiday schedule or healing for activities',
    loginDescription:
      ' There are many destinations for your holiday schedule or healing for activities',
    joining: 'Add poojari name',
  },
  constants: {
    role: {
      admin: 'ROLE_ADMIN',
      agent: 'ROLE_AGENT',
    },
    roleTypes: {
      admin: 'ROLE_ITEM_ADMIN',
      agent: 'ROLE_ITEM_AGENT',
      cms: 'ROLE_ITEM_CMS',
    },
    noInternet: 'Network Error!',
  },
  tabNames: {
    home: 'Home',
    search: 'search',
    ticket: 'ticket',
    favorites: 'favorites',
    profile: 'profile',
  },
  screenTitles: {},
  screenNames: {
    home: 'Home',
    category: 'Category',
    splash: 'Splash',
    signup: 'Signup',
    signup2: 'Signup2',
    signin: 'Signin',
    bottomTab: 'BottomTab',
    otpScreen: 'OtpScreen',
    homeDetails: 'HomeDetails',
    updatePassword: 'UpdatePassword',
    myTamples: 'MyTamples',
    addTample: 'AddTample',
    service: 'Services',
    seemore: 'Seemore',
    createPost: 'CreatePost',
    poojari: 'Poojari',
    events: 'Events',
    favlist: 'Favorite',
    occasions: 'Occasions',
    manage: 'Manage',
    calender: 'Calender',
    addevents: 'AddEvents',
    updateHome: 'UpdateHome',
    profile: 'Profile',
    splashscreen: 'Splash_Screen',
    addtemplenew: 'AddTempleNew',
    templeprofile: 'TempleProfile',
    viewprofile: 'ViewProfile',
    editprofile: 'EditProfile',
    addtemplekovela: 'AddTempleKovela',
    addtempleimage: 'AddTempleImage',
    newaddTemple: ' NewAddTemple',
    adminupdate: 'AdminUpdate',
    admindetails: 'AdminDetails',
    addemployee: 'AddEmployee',
    astrologer: 'Astrologer',
    idol: 'Idol',
    adminevents: 'AdminEvents',
  },
  homeHeader: {
    welcome: 'Welcome ',
  },
  homeTabs: {
    all: 'All',
    nearby: 'Nearby',
    popular: 'Popular',
    mostViewd: 'Most Viewed',
  },
  homeDetail: {
    donation: 'Donation',
    ticketBooking: 'Ticket Booking',
    poojaTicketBooking: 'Pooja Ticket Booking',
    accmodation: 'Accomodation',
  },
  other: {
    follow: 'Follow',
    unfollow: 'Unfollow',
    role: 'role is Required',
  },
};
